name: val_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.11
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#2d2d30"
  image: assets/logo_app.png
  android_12:
    image: assets/logo_app.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_app.png"